# Example for: model.assess_normalized_dope()
from modeller import *
from modeller.scripts import complete_pdb
import sys

pdb = sys.argv[1]
output = str(sys.argv[2]) + '.profile'

env = environ()
env.libs.topology.read(file='$(LIB)/top_heav.lib')
env.libs.parameters.read(file='$(LIB)/par.lib')

# Read a model previously generated by Modeller's automodel class
mdl = complete_pdb(env, pdb)

zscore = mdl.assess_normalized_dope()

s = selection(mdl)
s.assess_dope(output='ENERGY_PROFILE NO_REPORT', file=output,
              normalize_profile=True, smoothing_window=15)